#Plugin by INFOMCPE.RU(https://github.com/infomcpe)
#█──────██─█████─█─███─█─────█─███████─███████─█─█████─██─────██──────██───────██████─██████──█─────█─
#█─█████─██─███─██──█──██────█─█───────█─────█─█──███──█─█████─█─█████─█─████████████─█─────█─█─────█─
#█─█████─███─█─███──█──█─█───█─█───────█─────█─█─█─█─█─█─███████─█████─█─████████████─█─────█─█─────█─
#█──────█████─████──█──█──█──█─█████───█─────█─█─██─██─█─███████──────██─────████████─██████──█─────█─
#█─█████─████─████──█──█───█─█─█───────█─────█─█─█████─█─███████─███████─████████───█─█───█───█─────█─
#█─█████─████─████──█──█────██─█───────█─────█─█─█████─█─█████─█─███████─████████───█─█────█──█─────█─
#█──────█████─████─███─█─────█─█───────███████─█─█████─██─────██─███████───────██───█─█─────█──█████──
#█████████████████─────────────────────────────██████████████████████████████████████─────────────────


#↓Set language available: rus, eng
#↓Выбор языка доступно: rus, eng
lang: rus
#↓Refresh Interval signs (in seconds)
#↓Интервал обновления табличек (в секундах)
interval: 120
 
SignText: §f[§aITransfer§f]
---
 